### ISSUE TITLE
Error migrating database on first run with sqlite

### ISSUE THREAD

**Issue by riccardobl** [getAlby/lndhub.go#178] opened 2022-05-27 17:42 UTC
I am trying to run this locally with sqlite, but i am getting a migration error.
```bash
riccardo@riccardo-ws:~/Desktop/lndhub$ ./lndhub-0.7.0-linux-x86_64 
{"level":"fatal","time":"2022-05-27T19:34:45+02:00","message":"Error migrating database: SQL logic error: unknown database public (1)"}
```
lndhub-0.7.0-linux-x86_64 is the executable from the latest release but i've tried also to run the main branch and had the same issue.

This is the .env file

```bash
DATABASE_URI=file:data.db
LOG_FILE_PATH=
SENTRY_DSN=
JWT_SECRET=*************
JWT_ACCESS_EXPIRY=172800
JWT_REFRESH_EXPIRY=604800
LND_ADDRESS=127.0.0.1:10001
LND_MACAROON_HEX=*************
LND_CERT_HEX=*************
FIXED_FEE=10
```

The data.db file doesn't exist when i run the command, is there maybe something i need to do before to create it?

**Comment by bumi** [comment] 2022-05-27 18:40
Thanks for reporting this! I can confirm this problem and it seems it is an issue when we changed the initial migration to pure SQL.

Can you try this change if it works for you: https://github.com/getAlby/lndhub.go/commit/6173dcac090ed8aa666c1f250fb5a1256a7c1ae0

**Comment by riccardobl** [comment] 2022-05-27 19:07
It seems to be working. Thank you.

**Comment by riccardobl** [comment] 2022-05-27 20:17
Actually, i think there is more to this issue, it seems some api calls are failing when sqlite is used (maybe the db is not queried or update properly?).

Basically what i am doing is creating an invoice with `addinvoice` and then checking for payment with `checkpayment/hash`. \
This is the error i am getting 
`{"error":true,"code":8,"message":"Bad arguments"}` 
and if i check the balance it is zero even after i pay the invoice.

This happens only when sqlite is used, i've got a postgres container running in the meantime and the same code is working as expected it is used as database instead of sqlite.

**Comment by bumi** [comment] 2022-05-27 22:19
damn, sorry. Yes tests are also red with sqlite. 
Need to look into that what I broke there. It should work. 🙈
but good to hear you are not blocked and got it running with PG.

**Comment by kiwiidb** [comment] 2022-06-17 06:48
This issue can be fixed by replacing `SERIAL` with `INTEGER` everywhere in [this file](https://github.com/getAlby/lndhub.go/blob/main/db/migrations/20220115171101_init.up.sql#L2). However, by doing that you will no longer be able to use Postgresql, as the id column will no longer be generated by default as an auto-incrementing number. To do this, you should add `GENERATED ALWAYS AS IDENTITY` to the column definition, because you [should not use `SERIAL`](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial). But then this makes it again incompatible with SQLite. If we would have used GORM, then it would be possible, because that would abstract the database dialect away, but since we are writing SQL ourselves using Bun, it’s always going to cause problems if we are trying to support 2 dialects.

So affter thinking it through, I have decided that the best thing to do is to drop support for SQLite. It shouldn't be a problem for self-hosting support in the future because you can easily deploy a Postgres instance on an Umbrel / RaspiBlitz besides LNDhub.go, other projects like BTCPayServer do this as well.

**Closed** 2022-06-18 08:53 UTC
